// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetIPList():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function InitListener(arg1:main.Config):Promise<main.Json>;

export function LoadConfig():Promise<main.Config>;

export function SaveConfig(arg1:main.Config):Promise<main.Json>;
